name: Deploy Cloud Run (staging)
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      - run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/eob-backend ./backend
      - run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/eob-frontend ./frontend
      - run: gcloud run deploy eob-backend --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/eob-backend --region=${{ secrets.GCP_REGION }} --allow-unauthenticated
      - run: gcloud run deploy eob-frontend --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/eob-frontend --region=${{ secrets.GCP_REGION }} --allow-unauthenticated
